module.exports = [
  { type: "doc", id: "v1/anscer-anya-api" },
  {
    type: "category",
    label: "Home",
    link: { type: "doc", id: "v1/home" },
    items: [
      {
        type: "doc",
        id: "v1/api-home",
        label: "Home",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Authentication",
    link: { type: "doc", id: "v1/auth" },
    items: [
      {
        type: "doc",
        id: "v1/login",
        label: "Login",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Users",
    link: { type: "doc", id: "v1/users" },
    items: [
      {
        type: "doc",
        id: "v1/get-all-users",
        label: "Get a list of users",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/create-user",
        label: "Create a new user",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-current-user",
        label: "Get current user",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/reset-password",
        label: "Reset Password",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-user-by-id",
        label: "Get a user by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/update-user-by-id",
        label: "Update a user by ID",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "v1/delete-user-by-id",
        label: "Delete a user by ID",
        className: "api-method delete",
      },
    ],
  },
  {
    type: "category",
    label: "Maps",
    link: { type: "doc", id: "v1/maps" },
    items: [
      {
        type: "doc",
        id: "v1/get-all-maps",
        label: "Get a list of maps",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/create-map",
        label: "Create a new map",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-map-by-id",
        label: "Get a map by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/update-map-by-id",
        label: "Update a map by ID",
        className: "menu__list-item--deprecated api-method put",
      },
      {
        type: "doc",
        id: "v1/delete-map-by-id",
        label: "Delete a map by ID",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "v1/load-map",
        label: "Load Map in Roobt",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-active-map-and-data",
        label: "Get Active map and data",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Waypoints",
    link: { type: "doc", id: "v1/waypoints" },
    items: [
      {
        type: "doc",
        id: "v1/get-all-waypoints",
        label: "Get a list of waypoints",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/create-waypoint",
        label: "Create a new waypoint",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-waypoint-by-id",
        label: "Get a waypoint by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/update-waypoint-by-id",
        label: "Update a waypoint by ID",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "v1/delete-waypoint-by-id",
        label: "Delete a waypoint by ID",
        className: "api-method delete",
      },
    ],
  },
  {
    type: "category",
    label: "Zones",
    link: { type: "doc", id: "v1/zones" },
    items: [
      {
        type: "doc",
        id: "v1/get-all-zones",
        label: "Get a list of zones",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/create-zone",
        label: "Create a new zone",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-zone-by-id",
        label: "Get a zone by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/update-zone-by-id",
        label: "Update a zone by ID",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "v1/delete-zone-by-id",
        label: "Delete a zone by ID",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "v1/toggle-active-zone-by-id",
        label: "Toggle Active status of a zone by ID",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Missions",
    link: { type: "doc", id: "v1/missions" },
    items: [
      {
        type: "doc",
        id: "v1/get-all-missions",
        label: "Get a list of missions",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/create-mission",
        label: "Create a new mission",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/get-mission-by-id",
        label: "Get a mission by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "v1/update-mission-by-id",
        label: "Update a mission by ID",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "v1/delete-mission-by-id",
        label: "Delete a mission by ID",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "v1/initiate-mission-by-id",
        label: "Initiate a mission by ID",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Robot",
    link: { type: "doc", id: "v1/robot" },
    items: [
      {
        type: "doc",
        id: "v1/quick-goal",
        label: "Quick Goal",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/quick-goal-waypoint",
        label: "Quick Goal Waypoint",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/init-robot",
        label: "Initialize Robot",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "v1/quick-goal-marker",
        label: "Quick Goal to path Marker",
        className: "api-method post",
      },
    ],
  },
];
